### ISSUE TITLE
How does this compare to Spatie package?

### ISSUE THREAD

**Issue by steveoliverguild** [keepsuit/laravel-opentelemetry#10]
Hi Fabio,

I'm curious - how does this compare to https://github.com/spatie/laravel-open-telemetry ?

It looks like it has very similar goals - was there something about that package that didn't work for your needs?

Regards,

-Steve

**Comment by cappuc** [comment]
Hi Steve,

I started working at this package before the spatie was created, so it wasn't an option at the time.

Anyway I think the main difference is that this package is a wrapper over the OTEL sdk (so it should be compatible with official otel extensions) and the spatie one is written from scratch and doesn't directly use the official sdk.
