### ISSUE TITLE
Middleware to restrict traces or limit trace data

### ISSUE THREAD

**Issue by steveoliverguild** [keepsuit/laravel-opentelemetry#11]
The [Vinelab/tracing-laravel](https://github.com/Vinelab/tracing-laravel/blob/master/config/tracing.php#L32) package provides middleware to restrict traces or limit trace data for your application:

1. Excluded paths
2. Allowed headers
3. Sensitive headers
4. Sensitive input
5. Payload content types

I like how your package is implementing the OTEL SDK (and not just Zipkin), and think it would be a great addition to the feature set.  I may be able to provide a MR in the future, but have no intention or capacity to do so at this time.

What are your thoughts? 

Cheers,
-Steve

**Comment by cappuc** [comment]
These are all interesting things to add, I will look at it when I have some time.

If you find other interesting features to add, feel free to reply to this issue.

**Comment by cappuc** [comment]
Hi @steveoliverguild,

I was looking at the vinelab implementation and this are the changes I plan to make:

1. Excluded paths (there is already the setting to exclude paths in the middleware tracer)
2. Allowed headers (I'll add request and response headers to track in the middleware config)
3. Sensitive headers (It can be useful to track the presence of an header)
4. Sensitive input (Inputs are not included in the trace and should not be traced anyway)
5. Payload content types (same as input but for response body, should not be traced anyway)

So I plan to add only allowed headers and sensitive headers config
