### ISSUE TITLE
Route model binding issue when using \Keepsuit\LaravelOpenTelemetry\Support\HttpServer\TraceRequestMiddleware::class in global middlewares

### ISSUE THREAD

**Issue by baraka121** [keepsuit/laravel-opentelemetry#25]
Hi,

I encountered a bug after adding \Keepsuit\LaravelOpenTelemetry\Support\HttpServer\TraceRequestMiddleware::class to global middlewares. This has caused [route model binding](https://laravel.com/docs/10.x/routing#route-model-binding) to break, and disrupt the functionality of my application. (I'm using in 1.0.0-beta5 version).

Could you please investigate and provide a fix?

Thanks.

**Comment by cappuc** [comment]
Hi @baraka121,

I've added a test with route model binding but it works without errors.

If you can provide a failing test, I will look at it

**Comment by baraka121** [comment]
Thanks!

If an empty model class is created, the test will work. However, if Laravel's model substitution "magic" does not occur **(which is currently not happening in your test)**, the test will still run successfully.

You should expand the test to include cases where Laravel's model substitution "magic" **does occur**. This will ensure that the functionality is thoroughly tested and working as expected. Right now, this test doesn't accurately cover this scenario.

**Comment by cappuc** [comment]
I've added the test for route model binding in this [commit](https://github.com/keepsuit/laravel-opentelemetry/commit/04f28ecb05e4fe7bb0ca651b72f0ed8ab8ef1c97) and it passes.

If you can create a PR with a failing test, I will look at it.
With the information provided I can't reproduce your bug.
